apiVersion: v1
kind: Service
metadata:
  name: {{ include "coit-hc-ad-svc-release.fullname" . }}
  labels:
    {{- include "coit-hc-ad-svc-release.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "coit-hc-ad-svc-release.selectorLabels" . | nindent 4 }}
